# Generated by Django 2.1 on 2018-08-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeCapsule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffeeOrigin', models.CharField(max_length=25)),
                ('coffeeType', models.CharField(max_length=25)),
                ('additionDate', models.DateTimeField(verbose_name='addition coffee date')),
                ('expirationDate', models.DateTimeField(verbose_name='expiration coffee date')),
            ],
        ),
    ]
